version: '3.8'

services:
  riscv_dev:
    container_name: riscv_dev
    build: .
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    command: tail -f /dev/null